Add git-flow setup script; update README

diff --git a/gitflow-hooks/pre-flow-release-start b/gitflow-hooks/pre-flow-release-start
--- a/gitflow-hooks/pre-flow-release-start
+++ b/gitflow-hooks/pre-flow-release-start
@@ -1,6 +1,7 @@
 #!/bin/sh
 #
-# Verify main and develop are up-to-date before creating a release branch
+# Check main and develop are up-to-date before creating a release branch
+# Check for uncommitted changes
 
 git fetch
 
@@ -13,5 +14,10 @@ fi
 # Check that develop branch is up-to-date
 if [ $(git rev-parse develop) != $(git rev-parse origin/develop) ]; then
   echo "ERROR: Local develop branch not in sync with remote branch"
+  exit 1
+fi
+
+if ! git diff-index --quiet HEAD --; then
+  echo "ERROR: You have uncommitted changes. Please commit or stash them first."
   exit 1
 fi
