Feature/prep patch (#66)
Security:
- Add zizmor pre-commit hook
- Pin GitHub repos to full commit hashes
- Update permissions for GitHub Actions

GitHub Actions:
- Update python-publish.yml to use uv
- Fix incorrect bash regex checks in pr-check.yml
- Add some handling for Dependabot PRs to pr-check.yml
- Removed use of third party action for changelog.yml
- Named ruff GitHub Action

Dependabot:
- Add version updates for uv
- Reduce version updates to monthly
- Add 7-day cooldowns to all version updates (needs to be set at the ecosystem level, not the multi-ecosystem group level)
- Reconfigure version updates into a single multi-ecosystem group (i.e., one PR for all version updates) with PRs targeting develop

uv:
- Pin python version to 3.12 with .python-version
- Remove .python-version from .gitignore
- Add 7-day cooldown for uv (in pyproject.toml)
- Upgraded uv.lock using uv lock --upgrade

Misc:
- Update setup_gitflow.sh so releases and hotfixes merge to main instead of squash merge
- Update requires-python field in pyproject.toml
- Fix typo & unit test badge in README
- Minor updates to software release issue template
- Update changelog

---------

Co-authored-by: Rebecca Sutton Koeser <rlskoeser@users.noreply.github.com>

diff --git a/.github/workflows/changelog.yml b/.github/workflows/changelog.yml
--- a/.github/workflows/changelog.yml
+++ b/.github/workflows/changelog.yml
@@ -1,3 +1,5 @@
+# Inspired by the changelog-check-action (https://github.com/tarides/changelog-check-action)
+
 name: Check Changelog
 on:
   pull_request:
@@ -13,16 +15,36 @@ concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true
 
+env:
+  CHANGELOG: CHANGELOG.md
+  BASE_REF: ${{ github.base_ref }}
+  # Has no changelog label
+  HAS_LABEL: ${{ contains(github.event.pull_request.labels.*.name, 'no changelog') }}
+
 jobs:
   check-changelog:
     name: Verify Changelog Updated
     runs-on: ubuntu-latest
-    # for labeled/unlabeled actions, only run if it involves the "no changelog" label
+    # For labeled/unlabeled actions, only run if it involves the "no changelog" label
     if: >
       (contains(github.event.action, 'label') && github.event.label.name == 'no changelog')
       || ! contains(github.event.action, 'label')
     steps:
-      - name: Check changelog
-        uses: tarides/changelog-check-action@v3
+      - name: Checkout repository
+        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
         with:
-          changelog: CHANGELOG.md
+          persist-credentials: false
+          fetch-depth: 0
+
+      - name: Check changelog
+        run: |
+          if ${HAS_LABEL}; then
+            echo "Check passes, since 'no changelog' label is set"
+            exit 0
+          elif git diff --exit-code "origin/${BASE_REF}" -- "${CHANGELOG}"; then
+            echo "Error: User-visible changes should come with an entry in the changelog."
+            echo "For changes not user-visible, add the 'no changelog' label to override this behavior."
+            exit 1
+          else
+            echo "Check passes, changes detected in ${CHANGELOG}"
+          fi
diff --git a/.github/workflows/pr-check.yml b/.github/workflows/pr-check.yml
--- a/.github/workflows/pr-check.yml
+++ b/.github/workflows/pr-check.yml
@@ -17,12 +17,20 @@ jobs:
   validate-gitflow:
     name: Validate GitFlow branch rules
     runs-on: ubuntu-latest
-
+    env:
+      HEAD_REF: ${{ github.head_ref }}
     steps:
       - name: Check PRs to main
         if: github.base_ref == 'main'
         run: |
-          if [[ ${{ github.head_ref }} =~ "release/*" && ${{ github.head_ref }} =~ "hotfix/*" ]]; then
+          if [[ "$HEAD_REF" =~ ^(release|hotfix)/ ]]; then
+            echo "PASS: PRs from release and hotfix branches can target main"
+            exit 0
+          elif [[ ${HEAD_REF} =~ ^dependabot/ ]]; then
+            echo "ERROR: Cannot directly merge Dependabot updates"
+            echo "Add desired updates to a release, hotfix, or feature branch"
+            exit 1
+          else
             echo "ERROR: PRs targeting main must come from a release or hotfix branch"
             exit 1
           fi
@@ -30,7 +38,13 @@ jobs:
       - name: Check PRs to develop
         if: github.base_ref == 'develop'
         run: |
-          if [[ ${{ github.head_ref }} =~ "main" && ${{ github.head_ref }} =~ "feature/*" ]]; then
-            echo "ERROR: PRs targeting develop must come from main or a feature branch"
+          if [[ "$HEAD_REF" = "main" || "$HEAD_REF" =~ ^feature/ ]]; then
+            echo "PASS: PRs from main and feature branches can target develop"
+            exit 0
+          elif [[ "$HEAD_REF" =~ ^dependabot/ ]]; then
+            echo "PASS: PRs from Dependabot updates can target develop"
+            exit 0
+          else
+            echo "ERROR: PRs targeting develop must come from main, Dependabot updates, or a feature branch"
             exit 1
           fi
