Fix Pr Check GitHub Action workflow

diff --git a/.github/workflows/pr-check.yml b/.github/workflows/pr-check.yml
--- a/.github/workflows/pr-check.yml
+++ b/.github/workflows/pr-check.yml
@@ -23,7 +23,14 @@ jobs:
       - name: Check PRs to main
         if: github.base_ref == 'main'
         run: |
-          if [[ ${HEAD_REF} =~ "release/*" && ${HEAD_REF } =~ "hotfix/*" ]]; then
+          if [[ "$HEAD_REF" =~ "^(release|hotfix)/" ]]; then
+            echo "PASS: PRs from release and hotfix branches can target main"
+            exit 0
+          elif [[ ${HEAD_REF} =~ "^dependabot/" ]]; then
+            echo "ERROR: Cannot directly merge Dependabot security updates"
+            echo "Add desired updates to a release or hotfix branch"
+            exit 1
+          else
             echo "ERROR: PRs targeting main must come from a release or hotfix branch"
             exit 1
           fi
@@ -31,7 +38,13 @@ jobs:
       - name: Check PRs to develop
         if: github.base_ref == 'develop'
         run: |
-          if [[ ${HEAD_REF} =~ "main" && ${HEAD_REF} =~ "feature/*" ]]; then
-            echo "ERROR: PRs targeting develop must come from main or a feature branch"
+          if [[ "$HEAD_REF" == "main" || "$HEAD_REF" =~ "^feature/" ]]; then
+            echo "PASS: PRs from main and feature branches can target develop"
+            exit 0
+          elif [[ "$HEAD_REF" =~ "^dependabot/version-updates/" ]]; then
+            echo "PASS: PRs from Dependabot version updates can target develop"
+            exit 0
+          else
+            echo "ERROR: PRs targeting develop must come from main, Dependabot version updates, or a feature branch"
             exit 1
           fi
